# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

addons:
  apt:
    packages:
    - gfortran

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("FortranFiles"); Pkg.test("FortranFiles"; coverage=true)'

after_success:
  # build and deploy documentation
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
      julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("FortranFiles")); include(joinpath("docs", "make.jl"))';
    fi
  # push coverage results to Coveralls and Codecov
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      julia -e 'cd(Pkg.dir("FortranFiles")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
      julia -e 'cd(Pkg.dir("FortranFiles")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
